from copy import deepcopy


HEADACHE_POLICY = {
    "policy_name": "headache",
    "display_name": "Headache",
    "aliases": [
        "headache",
        "migraine",
        "head pain",
    ],
    "critical_followups": [
        "sudden_severe_onset",
        "neurologic_symptoms",
        "visual_changes",
        "confusion_or_ams",
        "fever_or_neck_stiffness",
        "head_trauma",
        "pregnancy_or_postpartum_context",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "location",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "photophobia",
        "phonophobia",
        "nausea_or_vomiting",
        "aura_features",
        "exertional_trigger",
        "positional_component",
        "new_or_progressive_pattern",
        "medication_overuse_context",
    ],
    "red_flags": [
        "thunderclap_headache",
        "focal_neurologic_deficit",
        "altered_mental_status",
        "fever_with_neck_stiffness",
        "post_traumatic_headache",
        "progressive_or_new_severe_pattern",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "location",
            "character",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 6,
    },
}


CHEST_PAIN_POLICY = {
    "policy_name": "chest_pain",
    "display_name": "Chest Pain",
    "aliases": [
        "chest pain",
        "chest pressure",
        "chest tightness",
    ],
    "critical_followups": [
        "shortness_of_breath",
        "syncope_or_presyncope",
        "rapid_worsening",
    ],
    "must_characterize": [
        "onset",
        "location",
        "duration",
        "severity",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "radiation",
        "nausea",
        "diaphoresis",
        "exertional_component",
    ],
    "red_flags": [
        "active_breathing_difficulty",
        "syncope_or_presyncope",
        "severe_symptom_intensity",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "location",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 5,
    },
}


ABDOMINAL_PAIN_POLICY = {
    "policy_name": "abdominal_pain",
    "display_name": "Abdominal Pain",
    "aliases": [
        "abdominal pain",
        "stomach pain",
        "belly pain",
        "stomach ache",
    ],
    "critical_followups": [
        "vomiting",
        "fever",
        "bloody_stool_or_melena",
        "pregnancy_or_postpartum_context",
        "syncope_or_presyncope",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "location",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "nausea",
        "diarrhea",
        "constipation",
        "urinary_symptoms",
        "last_oral_intake",
    ],
    "red_flags": [
        "persistent_vomiting",
        "blood_in_stool",
        "pregnancy_related_abdominal_pain",
        "severe_abdominal_pain_with_syncope",
        "fever_with_abdominal_pain",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "location",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 5,
    },
}


SHORTNESS_OF_BREATH_POLICY = {
    "policy_name": "shortness_of_breath",
    "display_name": "Shortness of Breath",
    "aliases": [
        "shortness of breath",
        "sob",
        "trouble breathing",
        "breathing difficulty",
    ],
    "critical_followups": [
        "chest_pain",
        "rapid_worsening",
        "syncope_or_presyncope",
        "fever",
        "wheezing",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "cough",
        "orthopnea",
        "leg_swelling",
        "exertional_component",
    ],
    "red_flags": [
        "active_breathing_difficulty",
        "shortness_of_breath_with_chest_pain",
        "shortness_of_breath_with_syncope",
        "rapidly_worsening_breathing",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 4,
    },
}


DIZZINESS_POLICY = {
    "policy_name": "dizziness",
    "display_name": "Dizziness",
    "aliases": [
        "dizziness",
        "lightheadedness",
        "feeling faint",
        "vertigo",
    ],
    "critical_followups": [
        "syncope_or_presyncope",
        "neurologic_symptoms",
        "chest_pain",
        "shortness_of_breath",
        "head_trauma",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "visual_changes",
        "palpitations",
        "positional_component",
        "nausea",
    ],
    "red_flags": [
        "dizziness_with_syncope",
        "dizziness_with_neurologic_deficit",
        "dizziness_with_chest_pain",
        "post_traumatic_dizziness",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 4,
    },
}


SORE_THROAT_POLICY = {
    "policy_name": "sore_throat",
    "display_name": "Sore Throat",
    "aliases": [
        "sore throat",
        "throat pain",
        "scratchy throat",
    ],
    "critical_followups": [
        "shortness_of_breath",
        "trouble_swallowing",
        "drooling",
        "fever",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "cough",
        "voice_change",
        "sick_contacts",
    ],
    "red_flags": [
        "airway_compromise_symptoms",
        "severe_trouble_swallowing",
        "drooling_with_sore_throat",
        "fever_with_worsening_throat_pain",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 4,
    },
}


BACK_PAIN_POLICY = {
    "policy_name": "back_pain",
    "display_name": "Back Pain",
    "aliases": [
        "back pain",
        "low back pain",
        "upper back pain",
    ],
    "critical_followups": [
        "neurologic_symptoms",
        "bowel_or_bladder_changes",
        "fever",
        "head_trauma",
        "rapid_worsening",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "location",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "radiation",
        "recent_heavy_lifting",
        "numbness_or_tingling",
    ],
    "red_flags": [
        "back_pain_with_neurologic_deficit",
        "back_pain_with_bowel_or_bladder_changes",
        "fever_with_back_pain",
        "post_traumatic_back_pain",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "location",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 5,
    },
}


NAUSEA_VOMITING_POLICY = {
    "policy_name": "nausea_vomiting",
    "display_name": "Nausea / Vomiting",
    "aliases": [
        "nausea",
        "vomiting",
        "nausea and vomiting",
        "throwing up",
        "feeling sick",
        "queasy",
        "i feel nauseous",
        "i keep throwing up",
        "can't keep anything down",
    ],
    "critical_followups": [
        "bloody_stool_or_melena",
        "chest_pain",
        "neurologic_symptoms",
        "fever",
        "rapid_worsening",
        "syncope_or_presyncope",
        "pregnancy_or_postpartum_context",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "last_oral_intake",
        "sick_contacts",
    ],
    "red_flags": [
        "gi_bleeding_with_nausea",
        "chest_pain_with_nausea",
        "neurologic_symptoms_with_vomiting",
        "fever_with_vomiting",
        "syncope_with_nausea",
        "pregnancy_related_vomiting",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 4,
    },
}


FEVER_POLICY = {
    "policy_name": "fever",
    "display_name": "Fever",
    "aliases": [
        "fever",
        "high temperature",
        "high temp",
        "running a fever",
        "i have a fever",
        "feel hot",
        "chills",
        "i have chills",
    ],
    "critical_followups": [
        "fever_or_neck_stiffness",
        "neurologic_symptoms",
        "shortness_of_breath",
        "chest_pain",
        "confusion_or_ams",
        "rapid_worsening",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "nausea_or_vomiting",
        "cough",
        "urinary_symptoms",
        "rash_or_petechiae",
        "sick_contacts",
    ],
    "red_flags": [
        "fever_with_neck_stiffness",
        "fever_with_neurologic_symptoms",
        "fever_with_respiratory_distress",
        "fever_with_altered_mental_status",
        "rapidly_worsening_fever_with_systemic_signs",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 4,
    },
}


SYNCOPE_POLICY = {
    "policy_name": "syncope",
    "display_name": "Syncope / Fainting",
    "aliases": [
        "syncope",
        "fainting",
        "fainted",
        "passed out",
        "blacked out",
        "loss of consciousness",
        "i passed out",
        "i blacked out",
        "i fainted",
        "i lost consciousness",
    ],
    "critical_followups": [
        "chest_pain",
        "shortness_of_breath",
        "palpitations",
        "rapid_worsening",
        "neurologic_symptoms",
        "head_trauma",
        "exertional_component",
        "prodrome_witnessed_loss_of_consciousness",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "diaphoresis",
        "nausea",
        "positional_component",
        "exertional_trigger",
    ],
    "red_flags": [
        "syncope_with_chest_pain",
        "syncope_with_palpitations",
        "exertional_syncope",
        "syncope_with_neurologic_deficit",
        "post_traumatic_syncope",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 4,
    },
}


PALPITATIONS_POLICY = {
    "policy_name": "palpitations",
    "display_name": "Palpitations",
    "aliases": [
        "palpitations",
        "heart racing",
        "heart pounding",
        "heart fluttering",
        "skipping beats",
        "irregular heartbeat",
        "my heart is racing",
        "i can feel my heart beating",
        "heart is pounding",
        "heart is fluttering",
    ],
    "critical_followups": [
        "chest_pain",
        "shortness_of_breath",
        "syncope_or_presyncope",
        "rapid_worsening",
        "diaphoresis",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "exertional_component",
        "positional_component",
    ],
    "red_flags": [
        "palpitations_with_chest_pain",
        "palpitations_with_syncope",
        "palpitations_with_dyspnea",
        "rapidly_worsening_palpitations",
        "palpitations_with_diaphoresis",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "timing",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 5,
    },
}


LEG_PAIN_SWELLING_POLICY = {
    "policy_name": "leg_pain_swelling",
    "display_name": "Leg Pain / Swelling",
    "aliases": [
        "leg pain",
        "leg swelling",
        "swollen leg",
        "calf pain",
        "my leg is swollen",
        "my leg hurts",
        "swollen calf",
        "leg is swollen",
        "leg cramps",
    ],
    "critical_followups": [
        "rapid_worsening",
        "calf_tenderness_or_warmth",
        "unilateral_leg_swelling",
        "shortness_of_breath",
        "chest_pain",
        "syncope_or_presyncope",
        "neurologic_symptoms",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "location",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "unilateral_vs_bilateral",
        "recent_immobility_or_travel",
        "recent_trauma_or_surgery",
        "recent_heavy_lifting",
    ],
    "red_flags": [
        "dvt_signs_unilateral_swelling_with_warmth",
        "pe_symptoms_with_leg_swelling",
        "rapid_worsening_suggesting_limb_ischemia",
        "neurologic_deficit_with_leg_pain",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "location",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 5,
    },
}


URINARY_SYMPTOMS_POLICY = {
    "policy_name": "urinary_symptoms",
    "display_name": "Urinary Symptoms",
    "aliases": [
        "urinary symptoms",
        "burning urination",
        "painful urination",
        "frequent urination",
        "blood in urine",
        "can't urinate",
        "trouble urinating",
        "dysuria",
        "uti",
        "urinary tract infection",
        "i can't pee",
        "it burns when i pee",
    ],
    "critical_followups": [
        "fever_or_neck_stiffness",
        "flank_pain",
        "hematuria",
        "urinary_retention",
        "rapid_worsening",
        "neurologic_symptoms",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "suprapubic_pain",
        "nausea_or_vomiting",
        "pregnancy_or_postpartum_context",
    ],
    "red_flags": [
        "fever_with_urinary_symptoms_suggesting_pyelonephritis",
        "flank_pain_with_urinary_symptoms",
        "hematuria_with_urinary_symptoms",
        "complete_urinary_retention",
        "neurologic_deficit_with_urinary_changes",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 4,
    },
}


COUGH_POLICY = {
    "policy_name": "cough",
    "display_name": "Cough",
    "aliases": [
        "cough",
        "coughing",
        "coughing up blood",
        "persistent cough",
        "dry cough",
        "wet cough",
        "i have a cough",
        "i keep coughing",
        "can't stop coughing",
    ],
    "critical_followups": [
        "shortness_of_breath",
        "chest_pain",
        "rapid_worsening",
        "hemoptysis",
        "fever_or_neck_stiffness",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "wheezing",
        "sick_contacts",
    ],
    "red_flags": [
        "hemoptysis",
        "cough_with_respiratory_distress",
        "cough_with_chest_pain",
        "rapidly_worsening_cough_with_fever",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "character",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 5,
    },
}


RASH_POLICY = {
    "policy_name": "rash",
    "display_name": "Rash",
    "aliases": [
        "rash",
        "skin rash",
        "hives",
        "breakout",
        "skin irritation",
        "itchy skin",
        "spots on skin",
        "i have a rash",
        "my skin broke out",
        "welts",
    ],
    "critical_followups": [
        "fever_or_neck_stiffness",
        "syncope_or_presyncope",
        "shortness_of_breath",
        "trouble_swallowing",
        "drooling",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "location",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "sick_contacts",
    ],
    "red_flags": [
        "petechial_rash_with_fever_suggesting_meningococcemia",
        "anaphylaxis_with_rash",
        "airway_compromise_with_rash",
        "rash_with_syncope",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "location",
            "character",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 6,
    },
}


ALTERED_MENTAL_STATUS_POLICY = {
    "policy_name": "altered_mental_status",
    "display_name": "Altered Mental Status",
    "aliases": [
        "confused",
        "confusion",
        "not acting right",
        "altered",
        "disoriented",
        "not making sense",
        "acting strange",
        "not themselves",
        "mental status change",
        "altered mental status",
    ],
    "critical_followups": [
        "sudden_severe_onset",
        "head_trauma",
        "fever_or_neck_stiffness",
        "shortness_of_breath",
        "syncope_or_presyncope",
        "rapid_worsening",
        "neurologic_symptoms",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "last_oral_intake",
        "sick_contacts",
        "nausea_or_vomiting",
    ],
    "red_flags": [
        "sudden_onset_altered_mental_status",
        "ams_with_head_trauma",
        "ams_with_fever_neck_stiffness",
        "ams_with_respiratory_distress",
        "rapidly_worsening_mental_status",
        "ams_with_neurologic_deficit",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 4,
    },
}


SEIZURE_POLICY = {
    "policy_name": "seizure",
    "display_name": "Seizure",
    "aliases": [
        "seizure",
        "seizures",
        "convulsion",
        "convulsions",
        "fit",
        "i had a seizure",
        "i was shaking uncontrollably",
        "i blacked out and shook",
        "i had a spell",
        "my body went stiff",
    ],
    "critical_followups": [
        "neurologic_symptoms",
        "head_trauma",
        "fever_or_neck_stiffness",
        "confusion_or_ams",
        "syncope_or_presyncope",
        "rapid_worsening",
        "prodrome_witnessed_loss_of_consciousness",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "timing",
        "course",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "seizure_history",
        "antiepileptic_compliance",
        "recent_sleep_deprivation",
        "recent_substance_use",
        "tongue_or_lip_biting",
        "incontinence_during_event",
        "postictal_confusion",
    ],
    "red_flags": [
        "new_onset_seizure",
        "seizure_with_head_trauma",
        "seizure_with_fever_neck_stiffness",
        "prolonged_or_recurrent_seizure_status_epilepticus",
        "postictal_neurologic_deficit",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "timing",
            "course",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 6,
    },
}


EYE_PAIN_POLICY = {
    "policy_name": "eye_pain",
    "display_name": "Eye Pain / Vision Change",
    "aliases": [
        "eye pain",
        "eye hurts",
        "vision change",
        "blurry vision",
        "vision loss",
        "seeing spots",
        "my eye hurts",
        "i can't see well",
        "double vision",
        "floaters",
        "flashes",
        "red eye",
        "eye problem",
    ],
    "critical_followups": [
        "visual_changes",
        "sudden_severe_onset",
        "floaters_or_flashes",
        "vision_loss_pattern",
        "recent_eye_trauma",
        "photophobia",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "location",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "eye_pain_type",
        "eye_discharge",
        "redness",
        "nausea",
        "headache_with_eye_pain",
        "contact_lens_use",
    ],
    "red_flags": [
        "sudden_vision_loss",
        "floaters_or_flashes_suggesting_retinal_detachment",
        "acute_angle_closure_glaucoma_pattern",
        "traumatic_eye_injury",
        "photophobia_with_severe_eye_pain",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "location",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 5,
    },
}


EAR_PAIN_POLICY = {
    "policy_name": "ear_pain",
    "display_name": "Ear Pain",
    "aliases": [
        "ear pain",
        "ear ache",
        "earache",
        "my ear hurts",
        "ear infection",
        "ear drainage",
        "can't hear",
        "hearing loss",
        "ringing in ears",
        "tinnitus",
        "ear is ringing",
    ],
    "critical_followups": [
        "fever_or_neck_stiffness",
        "neurologic_symptoms",
        "head_trauma",
        "hearing_loss_or_tinnitus",
        "ear_drainage_or_bleeding",
    ],
    "must_characterize": [
        "onset",
        "duration",
        "severity",
        "location",
        "character",
        "aggravating_factors",
        "relieving_factors",
        "associated_symptoms",
    ],
    "high_priority_followups": [
        "medications",
        "allergies",
        "sick_contacts",
    ],
    "red_flags": [
        "fever_with_ear_pain_suggesting_mastoiditis",
        "neurologic_deficit_with_ear_pain",
        "post_traumatic_ear_pain_with_hearing_loss",
        "ear_drainage_or_bleeding",
        "sudden_sensorineural_hearing_loss",
    ],
    "wrap_up_rule": {
        "type": "characterization_threshold",
        "require_all_critical": True,
        "required_characterization_targets": [
            "onset",
            "duration",
            "severity",
            "location",
            "character",
            "aggravating_factors",
            "relieving_factors",
            "associated_symptoms",
        ],
        "min_required_characterization_count": 6,
    },
}


COMPLAINT_POLICIES = {
    "headache":               HEADACHE_POLICY,
    "chest_pain":             CHEST_PAIN_POLICY,
    "abdominal_pain":         ABDOMINAL_PAIN_POLICY,
    "shortness_of_breath":    SHORTNESS_OF_BREATH_POLICY,
    "dizziness":              DIZZINESS_POLICY,
    "sore_throat":            SORE_THROAT_POLICY,
    "back_pain":              BACK_PAIN_POLICY,
    "nausea_vomiting":        NAUSEA_VOMITING_POLICY,
    "fever":                  FEVER_POLICY,
    "syncope":                SYNCOPE_POLICY,
    "palpitations":           PALPITATIONS_POLICY,
    "leg_pain_swelling":      LEG_PAIN_SWELLING_POLICY,
    "urinary_symptoms":       URINARY_SYMPTOMS_POLICY,
    "cough":                  COUGH_POLICY,
    "rash":                   RASH_POLICY,
    "altered_mental_status":  ALTERED_MENTAL_STATUS_POLICY,
    "seizure":                SEIZURE_POLICY,
    "eye_pain":               EYE_PAIN_POLICY,
    "ear_pain":               EAR_PAIN_POLICY,
}


def get_policy_dict(policy_name):
    """
    Return a deep copy of the policy definition so callers do not mutate
    the module-level source of truth.
    """
    policy = COMPLAINT_POLICIES.get(policy_name)

    if policy is None:
        return None

    return deepcopy(policy)


def get_all_policy_dicts():
    """
    Return a deep copy of all policies keyed by policy_name.
    """
    return deepcopy(COMPLAINT_POLICIES)
