from copy import deepcopy


FACET_ORDER = [
    "chief_complaint_primary",
    "other_concerns",
    "hpi",
    "pertinent_positives",
    "pertinent_negatives",
    "pmh_psh",
    "medications",
    "allergies",
    "social_factors",
    "missing_clarifications",
    "flags",
]


INTAKE_TEMPLATE = {
    "chief_complaint_primary": None,
    "other_concerns": [],
    "hpi": {
        "summary": None,
        "onset": None,
        "location": None,
        "duration": None,
        "timing": None,
        "course": None,
        "character": None,
        "severity": None,
        "aggravating_factors": [],
        "relieving_factors": [],
        "associated_symptoms": [],
        "context": None,
    },
    "pertinent_positives": [],
    "pertinent_negatives": [],
    "pmh_psh": {
        "past_medical_history": [],
        "past_surgical_history": [],
    },
    "medications": [],
    "allergies": [],
    "social_factors": [],
    "missing_clarifications": [],
    "flags": [],
    "policy_answers": {
        "sudden_severe_onset": None,
        "neurologic_symptoms": None,
        "neurologic_symptom_terms": [],
        "visual_changes": None,
        "confusion_or_ams": None,
        "fever_or_neck_stiffness": None,
        "head_trauma": None,
        "pregnancy_or_postpartum_context": None,
        "photophobia": None,
        "phonophobia": None,
        "nausea_or_vomiting": None,
        "aura_features": [],
        "exertional_trigger": None,
        "positional_component": None,
        "new_or_progressive_pattern": None,
        "medication_overuse_context": None,
        "shortness_of_breath": None,
        "syncope_or_presyncope": None,
        "rapid_worsening": None,
        "radiation": [],
        "nausea": None,
        "diaphoresis": None,
        "exertional_component": None,
        "vomiting": None,
        "fever": None,
        "bloody_stool_or_melena": None,
        "diarrhea": None,
        "constipation": None,
        "urinary_symptoms": None,
        "last_oral_intake": None,
        "wheezing": None,
        "cough": None,
        "orthopnea": None,
        "leg_swelling": None,
        "palpitations": None,
        "trouble_swallowing": None,
        "drooling": None,
        "voice_change": None,
        "sick_contacts": None,
        "bowel_or_bladder_changes": None,
        "recent_heavy_lifting": None,
        "numbness_or_tingling": None,
        "chest_pain": None,
        # Tier 1 new policy targets
        "prodrome_witnessed_loss_of_consciousness": None,
        "hemoptysis": None,
        "rash_or_petechiae": None,
        "calf_tenderness_or_warmth": None,
        "unilateral_leg_swelling": None,
        "unilateral_vs_bilateral": None,
        "recent_immobility_or_travel": None,
        "recent_trauma_or_surgery": None,
        "flank_pain": None,
        "hematuria": None,
        "urinary_retention": None,
        "suprapubic_pain": None,
        "floaters_or_flashes": None,
        "vision_loss_pattern": None,
        "recent_eye_trauma": None,
        "eye_pain_type": None,
        "eye_discharge": None,
        "redness": None,
        "headache_with_eye_pain": None,
        "contact_lens_use": None,
        "hearing_loss_or_tinnitus": None,
        "ear_drainage_or_bleeding": None,
        "seizure_history": None,
        "antiepileptic_compliance": None,
        "recent_sleep_deprivation": None,
        "recent_substance_use": None,
        "tongue_or_lip_biting": None,
        "incontinence_during_event": None,
        "postictal_confusion": None,
    },
    "conversation_meta": {
        "visit_id": None,
        "turn_count": 0,
        "language": "en",
        "acuity_signal": [],
        "intake_complete": False,
        "last_question_intent": None,
        "last_question_target": None,
        "last_question_text": None,
        "last_answer_status": None,
        "user_requested_stop": False,
        "early_exit_reason": None,
        "natural_completion_ready": False,
        "question_status": {},
        "transcript": [],
    },
    "derived_outputs": {
        "patient_friendly_summary": None,
        "clinical_handoff_summary": None,
    },
    "future_context": {
        "ehr_data": None,
        "prior_encounters": None,
        "problem_list": None,
        "recent_labs": None,
        "recent_imaging": None,
        "external_documents": None,
    },
}


def make_empty_intake():
    return deepcopy(INTAKE_TEMPLATE)